const express = require("express");
const router = express.Router();


const crudController = require("../controllers/CRUDController");
const SalesController = require("../controllers/SalesController");






//Sales CRUD

// create
router.post("/CreateData",crudController.createSalesList);

//Read 
router.get("/ReadData",crudController.ReadSalesList);

//Read By ID
router.get("/ReadByID/:id", crudController.ReadByID);

//Delete 
router.delete("/deleteData/:id", crudController.deleteSalesList);

//Update
router.post("/updateData/:id",crudController.updateSalesList);



//Sales Analytics

// Calculate and return the total revenue generated by all sales transactions.
router.get("/sales/total-revenue",SalesController.getTotalRevenue);


// Find and return the total quantity sold for each product.
router.get("/sales/quantity-by-product",SalesController.getQuantityByProduct);


// Retrieve the top 5 products with the highest total revenue, 
//along with their total revenue values.
router.get("/sales/top-products",SalesController.getHighestTotalRevenue);


// Calculate and return the average price of products sold.
router.get("/sales/average-price",SalesController.getAveragePrice);


// Group the sales data by month and year and calculate the total revenue for each month-year combination.
router.get("/sales/revenue-by-month",SalesController.getRevenueByMonthYear);

//Find and return the product that had the highest quantity sold on a single day.
router.get("/sales/highest-quantity-sold",SalesController.getHighestQuantitySold);


// Calculate and return the total salary expense for each department.
router.get("/sales/department-salary-expense",SalesController.getDepartmentSalaryExpense);






module.exports=router;